### PR TITLE
Added test fiddles. Added comments in content.js

### PR DESCRIPTION
**Pull request by ritesh-nitjsr**
-  Link to fiddles for testing the extension added in the README file

-  Added comments in the content.js file

### CODE REVIEW

**Comment by djr-jsr** [comment]
I saw that you made the changes in your master branch. Its a bad practice. Its better to keep your master synced with the upstream master and commit your changes on a new branch.

**Comment by ritesh-nitjsr** [comment]
Oh okay. Thanks for the suggestion. I'll keep this in mind from the next time.

**Comment by djr-jsr** [comment]
Nice work. Try to implement toggle cut/copy option when clicked on the icon next.

**Comment by ritesh-nitjsr** [comment]
@djr-jsr Thanks. I'm working on the toggling feature.

**Comment by djr-jsr** [comment]
Your previous branch from which you had a pull request seems deleted. Hence the webpages are still not merged. Make a new PR for the webpages.

**Comment by ritesh-nitjsr** [comment]
@djr-jsr The link of the fiddles of those webpages are already in the README. Do we need the html files as well??

**Comment by djr-jsr** [comment]
Yes we need them. Just in case if we need to document them all together in one place.

**Pull request merged**
