### PR TITLE
Added webpages to test the chrome extension

### PR DESCRIPTION
**Pull request by ritesh-nitjsr**
Simple webpages to test the extension have been added.

### CODE REVIEW

**Comment by djr-jsr** [comment]
- [ ] Add a few comments explaining what the code does.
- [ ] Make and provide links to fiddles for the html codes.

**Comment by ritesh-nitjsr** [comment]
@djr-jsr shall I provide the links of the fiddles through text files? Or there's a better way to do so?

**Comment by ritesh-nitjsr** [comment]
@djr-jsr And what is the need of the zip file in your repository. I mean, do we have to make respective changes in the zip file as well??

**Comment by djr-jsr** [comment]
No that is nothing. I will remove it.

**Comment by ritesh-nitjsr** [comment]
@djr-jsr and what about the fiddles?? I've created it, how to provide the links?

**Comment by djr-jsr** [comment]
Add the fiddles in README.

**Pull request closed without merging**
